name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: authentification_team
          POSTGRES_PASSWORD: authentification_pwd
          POSTGRES_DB: authentification
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev
      - name: Copy empty .env.example to .env
        run: |
          cp .env.example .env
      - name: Run linting
        run: |
          pipenv run black --check .
          pipenv run flake8
          pipenv run isort . --check
      - name: Run the unit tests
        run: |
          pipenv run python manage.py test
